### ISSUE TITLE
troubleshoot "problem retrieving classes"

### ISSUE THREAD

**Issue by graybeal** [ncbo/bioportal-project#158]
The "problem retrieving classes" message in http://bioportal.bioontology.org/ontologies/PR seems unusual, because that is not exactly a flat ontology. (Of the 317,364 classes, one class has 99,224 (make it a root?), and 22,098 classes have a single child.)

See if we can understand why it produces this error, and what we can do to cope with or work around the error. (Until we actually have some decent display for flat and huge ontologies—see https://github.com/ncbo/bioportal-project/issues/157.)

**Comment by jvendetti** [comment]
The latest submission of this ontology (no. 77) was changed from OBO to OWL format. Our system wasn't able to handle the OWL format in a manner similar to what is described in #125. The shelter-in-place directive makes it difficult to offer more detail here, due to the prohibitively long time it takes to download ontology source  and log files > 1GB from home.

I created a new submission (no. 78) that reverts to the OBO format, which the system handles w/out errors. The class tree is visible again.
