### ISSUE TITLE
Remove spam ontology CHARITYAUER

### ISSUE THREAD

**Issue by caufieldjh** [ncbo/bioportal-project#300]
See https://bioportal.bioontology.org/ontologies/CHARITYAUER

**Comment by jvendetti** [comment]
Created by `charityauer` account.

@mdorf, @alexskr - I know this can be deleted manually, but I'd rather use our spam deletion script in order to remove all artifacts created by this account. The script appears to be broken in production (https://github.com/ncbo/ncbo_cron/issues/75). Could one of you please have a look at it?

**Comment by jvendetti** [comment]
CHARITYAUER has been deleted
