### ISSUE TITLE
library requests for browse page

### ISSUE THREAD

**Issue by graybeal** [ncbo/bioportal-project#55]
Michelle asks for 3 changes in Biblioportal:
1) the sample text in the "Search for a class" entry box: change to say "Enter a class, e.g. Work"
2) the sample text in the "Find an ontology" entry box: change to say "Start entering ontology name, e.g. BIBFRAME, then..."
3) when browsing ontologies, where do the Entry Type checkbox values come from? can you remove CIMI Model and NLM Value Set?

Ideally these could be in place well before Dec 12.

**Comment by mdorf** [comment]
implemented 3.

**Comment by jvendetti** [comment]
Numbers 1 and 2 above refer to the placeholder text in the text area components on the [home](http://bioportal.bioontology.org/) and [search](http://bioportal.bioontology.org/search) pages in the BioPortal UI. Pushed code to bioportal_web_ui (https://github.com/ncbo/bioportal_web_ui/commit/567743073c46803db71fdd94c6bf68d5c9432de0) and bioportal_config (https://github.com/ncbo/bioportal_config/commit/b8e5c9b14ac80dd31cf22b4c031f17493c67308f) to facilitate request for custom placeholder text. The text is now pulled from the locales file ([en.rb](https://github.com/ncbo/bioportal_config/blob/master/bioportal_web_ui/config/locales/en.rb)).

@alexskr - the next time you do a deployment of the Biblioportal instance of the virtual appliance, you can customize the placeholder text as Michelle requested above in config/locales/en.rb.

**Comment by michelleif** [comment]
Additional requests, can you do these before December 11th?
1. title of web page is SULAIR Biblioportal, please change to just Biblioportal
2. can you change the blue color of the banner bar to red?
3. I want to delete one of the ontologies, how do I do that? I have admin login... http://biblio.ontoportal.org/ontologies/STY

**Comment by graybeal** [comment]
Re #2, you'll need to specify the exact color triple, please. Enter 'color picker' into Google and use the tool that pops up, or one of the other tools referenced. Many will let you pick a color on your screen.

As the BioPortal ontology 'O' is based in blue, there may be a technical and/or administrative challenge to making it co-exist gracefully with a red banner bar. I will let the team handle the technical challenge, and I'll follow up on our branding policy.

**Comment by michelleif** [comment]
thanks for pointing out it might not be so straightforward.
exact color is:
Hex:#B1040E
if it proves too difficult, we can wait on this one and instead give it more thought (and even learn to change this ourselves)
idea is to make Biblioportal instantly recognizable as different from BioPortal, so you know for sure you are in Biblioportal

**Comment by graybeal** [comment]
yes AgroPortal did similar, so I'm pretty sure we can do it. We'll just need to change the blues to corresponding reds, assuming branding allows.

**Comment by graybeal** [comment]
I have word, we're good to go policy wise.

**Comment by alexskr** [comment]
- Numbers 1 and 2 above refer to the placeholder text in the text area components is released to biblioportal
- SULAIR is removed

**Comment by michelleif** [comment]
fabulous, thanks! one little thing: the screen says "Welcome to Biblioportal", the site title in browser says "Welcome to the Biblioportal", can you please remove "the" so it's consistent.

also the layout of the page seems to have changed (search for term and search for ontology are no longer next to each other), not sure if this is intentional, so wanted to let you know.

**Comment by alexskr** [comment]
i will punt the request to change page title of the home page from  "Welcome to the #{$ORG_SITE}"   to "Welcome to #{ORG_SITE}"  to @jvendetti.

**Comment by jvendetti** [comment]
This is in regard to the [comment above](https://github.com/ncbo/bioportal-project/issues/55#issuecomment-349085473) about changing the colors in BioPortal.

Modifying colors is an entirely different matter than making textual changes in the user interface. Text snippets are read from a configuration file at run time. This is standard practice in modern web frameworks, e.g., Rails, because it allows for easy internationalization, i.e., the ability to display menu items and other text in a variety of languages. It's straightforward to deploy a BioPortal virtual appliance with a configuration file where simple edits are made to the text (this is what Alex has done when he deployed Bibioportal).

Colors however, are part of the source code. The [AgroPortal](https://github.com/agroportal) project that John mentions above had a software developer on staff that forked (made a copy of) the BioPortal code base and made changes to the user interface. When AgroPortal is deployed, it's running with code that has diverged from the main BioPortal code base and is maintained externally by the AgroPortal group.

I don't know what the makeup of the library group is. Do you have an organization on GitHub where repositories can be forked to? Do you have a developer on staff that can fork/modify/maintain custom BioPortal UI code? Are you asking us to do these things for you? I think more clarification is needed here.

**Comment by jvendetti** [comment]
@alexskr - the next time you deploy Biblioportal, you can edit [line 10](https://github.com/ncbo/bioportal_config/blob/master/bioportal_web_ui/config/locales/en.rb#L10) of the en.rb locales file to change the title text on the home page as Michelle requested above.

Code is deployed to master branches (in these commits:  https://github.com/ncbo/bioportal_config/commit/d77ed21e8b726b277d9fb7dd50535bfb8699ce80, https://github.com/ncbo/bioportal_web_ui/commit/7dc7d5979acc50dc9531f0eea933674bf44a165f) and the UI is released in production, so you're good to go on this request.

**Comment by michelleif** [comment]
Hi, please advise on how to delete ontologies that we don't need, see #3 above

**Comment by mdorf** [comment]
@michelleif, you can delete an ontology by using the admin tool (see attachment):
1. Navigate to http://biblio.ontoportal.org/admin
2. Click on the Ontology Administration tab
3. On the top menu "View Ontologies" select "All". STY should now be visible in the grid.
4. Select the ontology row from the grid.
5. On the top menu "Apply to Selected Rows:", choose "Delete".
<img width="1493" alt="screen shot 2017-12-06 at 12 05 13 pm" src="https://user-images.githubusercontent.com/2042070/33682996-3a1a9cc2-da7e-11e7-9b83-4cb96b45ae2e.png">

**Comment by jvendetti** [comment]
All modifications / questions posed in this issue have been addressed / answered.

**Comment by michelleif** [comment]
Hi again, re # 3 in original request, it looks like CIMI and NLM were removed on **BioPortal**, I only want them removed from Biblioportal

**Comment by graybeal** [comment]
We determined that these were actually not useful at this time on BioPortal, and so the fastest way to get you what you wanted was to implement the change on BioPortal first. We plan to propagate that change to BiblioPortal.

**Comment by jvendetti** [comment]
CIMI and NLM no longer show up in Biblioportal (the propagation has already happened).
