### ISSUE TITLE
MDDB not in UMLS

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#81]
**IMPORTANT:** [MDDB](https://bioportal.bioontology.org/ontologies/MDDB/?p=summary) should be removed as one of the ontologies that is processed as part of the UMLS import. It's been removed from the UMLS distribution as of 2017AB. When we performed the last import of 2018AA, we created a new submission for MDDB that was mostly empty and received a [complaint from the user community](http://ncbo-support.2288202.n4.nabble.com/bioontology-support-BioPortal-Feedback-from-Ashleigh-Lewis-tp4656572p4656574.html) that we were no longer serving correct content.

Going forward, there should be a manual step that's performed before each import where we compare the [list of ontologies we process](https://github.com/ncbo/umls2rdf/blob/master/umls.conf) with what's actually in the UMLS distribution.

**Comment by graybeal** [comment]
I'm retitling this issue to ' MDDS not in UMLS' and referring to it in a new Load UMLS 2018AB issue, to be defined.

**Comment by graybeal** [comment]
I would like to make the argument that we handle this situation slightly differently. 

This is a valuable resource, and I propose we continue to provide it, but make clear it is no longer a UMLS resource. 

We obtained it under a valid license (that does not have any time constraints) and can continue to provide it under that license. People have pointed to MDDB URLs in BioPortal for a long time, and continue to access its contents. We should not cause these URLs to become invalid simply because UMLS no longer packages the content.

So rather than remove it, we should change the license terms to say 'This ontology is no longer included in the UMLS distribution; an updated paid version can be obtained from the vendor, see <url link here>. This ontology was made available by UMLS, and those license terms continue to apply. The terms of the UMLS license are available at https://uts.nlm.nih.gov/license.html.'

We should change the status (if that doesn't change the visibility) to indicate it is no longer a production ontology.

**Comment by jvendetti** [comment]
@graybeal - could you have a quick look at [MDDB in staging](http://stage.bioontology.org/ontologies/MDDB) and let me know if the license text looks OK to you?

**Comment by graybeal** [comment]
It’s great, but I just realized it’s confusing too.

The first sentence should start “The MDDB ontology is…”. The second sentence should start “The older version of the MDDB ontology presented here by BioPortal is from the 2017AA UMLS distribution, and those…”

Does that make sense?

Sorry and thanks!

John

________________________________

**Comment by jvendetti** [comment]
@graybeal - no problem, I made those adjustments to the text. It's [available now](http://stage.bioontology.org/ontologies/MDDB) in staging if you want to have another look.

**Comment by jvendetti** [comment]
Addressed by this commit: https://github.com/ncbo/bioportal_config/commit/38cce41e613501cf3bbcfeb098791f7afac9987c.
